FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
  python3-dev \
  python3-pip \
  libgl1 \
  libglib2.0-0 \
  libx11-6 \
  libxext6 \
  libsm6 \
  libxrender1 \
  x11-apps \
  && rm -rf /var/lib/apt/lists/*

ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1

WORKDIR /app-game

COPY . /app-game

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir pygame opencv-python numpy

CMD [ "python", "smart_bird.py" ]
